import { StoryTemplate } from '@/types';

export const STORY_TEMPLATES: StoryTemplate[] = [
  {
    id: 'forest-whisper',
    title: 'Le murmure de la forêt',
    cover_image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=300&h=400&fit=crop',
    category: 'aventure',
    description: 'Une aventure mystique dans une forêt enchantée',
    tags: ['Nature', 'Mystère', 'Magie'],
    isFavorite: false,
    difficulty: 'medium',
    estimated_time: 5,
    illustration_style: 'fantasy',
  },
  {
    id: 'three-princesses',
    title: 'Les Trois Princesses de la Vallée Dorée',
    cover_image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300&h=400&fit=crop',
    category: 'romance',
    description: 'Un conte de princesses courageuses dans un royaume magique',
    tags: ['Princesses', 'Courage', 'Amitié'],
    isFavorite: true,
    difficulty: 'easy',
    estimated_time: 4,
    illustration_style: 'fairy-tale',
  },
  {
    id: 'flame-guardian',
    title: 'Le Gardien des Flammes',
    cover_image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=300&h=400&fit=crop',
    category: 'aventure',
    description: 'Un jeune héros protège son village des forces obscures',
    tags: ['Héros', 'Feu', 'Protection'],
    isFavorite: false,
    difficulty: 'hard',
    estimated_time: 6,
    illustration_style: 'epic',
  },
  {
    id: 'lily-moon-rabbit',
    title: 'Lily et le Lapin de Lune',
    cover_image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop',
    category: 'comédie',
    description: 'Une aventure amusante avec un lapin magique',
    tags: ['Amitié', 'Lune', 'Magie'],
    isFavorite: true,
    difficulty: 'easy',
    estimated_time: 3,
    illustration_style: 'cute',
  },
  {
    id: 'autumn-secrets',
    title: 'Les Secrets d\'Automne',
    cover_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=400&fit=crop',
    category: 'mystère',
    description: 'Un mystère à résoudre dans une forêt automnale',
    tags: ['Mystère', 'Automne', 'Découverte'],
    isFavorite: false,
    difficulty: 'medium',
    estimated_time: 5,
    illustration_style: 'atmospheric',
  },
  {
    id: 'shadow-keeper',
    title: 'Le Gardien des Ombres',
    cover_image: 'https://images.unsplash.com/photo-1502780402662-acc01917949e?w=300&h=400&fit=crop',
    category: 'mystère',
    description: 'Une histoire sombre et mystérieuse pleine de suspense',
    tags: ['Ombres', 'Mystère', 'Suspense'],
    isFavorite: false,
    difficulty: 'hard',
    estimated_time: 7,
    illustration_style: 'dark',
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'Tous', color: '#6B3FA0' },
  { id: 'aventure', label: 'Aventure', color: '#FF9800' },
  { id: 'romance', label: 'Romance', color: '#E91E63' },
  { id: 'comédie', label: 'Comédie', color: '#4CAF50' },
  { id: 'mystère', label: 'Mystère', color: '#9C27B0' },
] as const;